### ISSUE TITLE
evemail proxy cannot send mail

### ISSUE THREAD

**Issue by leonhess** [antihax/evedata#11]
I tried sending a mail to one of my alts. I simply put his name into the recipient field, but it gave this error:
![img_0840](https://user-images.githubusercontent.com/32615985/39638129-83a69df2-4fc5-11e8-9f76-549034a87375.jpg)

**Comment by antihax** [comment]
Has to be a character ID.
I am hoping to find an LDAP solution to provide addressbook lookups to help
with this.

**Comment by leonhess** [comment]
ah ok, thanks

**Comment by leonhess** [comment]
just tried characterID and it gives me the same error

**Comment by antihax** [comment]
I am not having issues sending mails currently. However if a CSPA charge is set, it will fail to send. Trying to see if i can pipe what errors occur up through SMTP.
