### ISSUE TITLE
503 server is unavailable continually

### ISSUE THREAD

**Issue by soutpiel385** [antihax/evedata#24]
hey,

So for the last few weeks  -  it seems that since you added the ads - the several functions are "503 Service Unavailable
No server is available to handle this request. "

Unable to authenticate from Chrome or Edge to Eve authentication across 2 computers.  Unable to view market orders.

Im glad your monetizing your site, you deserve it.

**Comment by antihax** [comment]
The ads have been there for years.
Its a DNS issue in the cluster for some reason, put something in to remediate it.
