### ISSUE TITLE
LP/Isk store broken

### ISSUE THREAD

**Issue by kennyparker1337** [antihax/evedata#9]
The LP/isk function is completely broken at the moment because it does not take into the account the isk you must put in while buying many items from the LP store.

Example: Federation Navy Command Mindlink in the Federation Navy (Gallente) LP store is listed as an isk cost of 100mil because of the other command links you must buy first. However, the real price is 200mil because in the LP store it costs 100mil AND 100,000 lp. So the true lp/isk is around half of what it's listed as. Around 600 lp/isk not 1800.

**Comment by antihax** [comment]
interesting. I'll check into this as it should be factoring buy prices of items.

**Comment by kennyparker1337** [comment]
Easier example:
The listed isk price for **Limited Memory Augmentation - Beta** in the **Federation Navy** LP store is 0. However, in-game the cost is 2,500,000 isk from the LP store as well as 2,500 LP.

At the current lp/isk rating of 1,752 that means the selling price is calculated at 4,380,000.
However, if you deduct the 2,500,000 isk cost, the true lp/isk value is 752 not 1,752.

**Comment by antihax** [comment]
```ON DUPLICATE KEY UPDATE iskCost=VALUES(akCost),iskCost=VALUES(akCost)```

That would do it.

**Comment by kennyparker1337** [comment]
You fixed it and it's absolutely amazing now. I will be using it daily. Thx for all your hard work and for responding so quick to me.

**Comment by kennyparker1337** [comment]
I believe you fixed everything up. I see no problems now and everything is the correct lp/isk. Thx.

**Comment by antihax** [comment]
Awesome, thanks for letting me know!
